package ma.fstm.ilisi.gestioncantact.model.bo;
// Generated 20 mars 2022 à 00:15:36 by Hibernate Tools 5.4.7.Final

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private int id;
	private Type type;
	private String nom;
	private String prenom;
	private String numero;

	public Contact() {
	}
   
	public Contact( String nom, String prenom, String numero,Type type) {
		
		this.type = type;
		this.nom = nom;
		this.prenom = prenom;
		this.numero = numero;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}
	@Override
	public String toString() {
		return " [id=" + id + ", tele=" + numero + ", nom=" + nom + ", prenom=" + prenom + "]";
	}


}
