package ma.fstm.ilisi.gestioncantact.model.bo;
// Generated 20 mars 2022 à 00:15:36 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

	private String type;
	private Set contacts = new HashSet(0);

	public Type() {
	}

	public Type(String type) {
		this.type = type;
	}

	public Type(String type, Set contacts) {
		this.type = type;
		this.contacts = contacts;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getContacts() {
		return this.contacts;
	}

	public void setContacts(Set contacts) {
		this.contacts = contacts;
	}
	@Override
	public String toString() {
		return type;
	}
}
